tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "rcmdnk/file"
brew "jpeg"
brew "libpng"
brew "libtiff"
brew "autoconf"
brew "automake"
brew "bat"
brew "icu4c"
brew "boost"
brew "gettext", link: false
brew "pcre"
brew "pkg-config"
brew "cmake"
brew "libyaml"
brew "cocoapods"
brew "cscope"
brew "direnv"
brew "exa"
brew "fastlane"
brew "fd"
brew "fish"
brew "fzf"
brew "gh"
brew "ghq"
brew "gibo"
brew "gist"
brew "git"
brew "gnu-sed"
brew "go"
brew "openjdk"
brew "gradle"
brew "lua"
brew "highlight"
brew "libplist"
brew "libtasn1"
brew "libusb"
brew "libusbmuxd"
brew "libimobiledevice"
brew "libzip"
brew "ideviceinstaller"
brew "libtool"
brew "imagemagick"
brew "jemalloc"
brew "jq"
brew "kubernetes-cli"
brew "libevent"
brew "libpq"
brew "librsvg"
brew "libsigsegv"
brew "unibilium"
brew "libtermkey"
brew "libuv"
brew "libvterm"
brew "libxml2"
brew "llvm"
brew "macvim"
brew "mas"
brew "mitmproxy"
brew "msgpack"
brew "neovim"
brew "nginx"
brew "optipng"
brew "postgresql"
brew "pup"
brew "pv"
brew "qt"
brew "ruby-build"
brew "rbenv"
brew "rbenv-communal-gems"
brew "ripgrep"
brew "skaffold"
brew "the_silver_searcher"
brew "tig"
brew "utf8proc"
brew "tmux"
brew "tree"
brew "watch"
brew "wget"
brew "yarn"
brew "yq"
brew "rcmdnk/file/brew-file"
cask "alfred"
cask "bartender"
cask "docker"
cask "figma"
cask "firefox"
cask "google-chrome"
cask "google-japanese-ime"
cask "insomnia"
cask "iterm2"
cask "jasper"
cask "kap"
cask "karabiner-elements"
cask "meetingbar"
cask "notion"
cask "rectangle"
cask "spotify"
cask "steermouse"
cask "visual-studio-code"
cask "zoom"
mas "1Password 7", id: 1333542190
mas "Dato", id: 1470584107
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Kindle", id: 405399194
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Todoist", id: 585829637
mas "Unsplash Wallpapers", id: 1284863847
