[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = 'context_filetype.vim'
on_i = 1
hook_source = '''
  let g:deoplete#enable_at_startup = 1
  source ~/.config/nvim/plugins/deoplete.rc.vim
'''

[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
hook_source = '''
  source ~/.config/nvim/plugins/denite.rc.vim
'''

[[plugins]]
repo = 'Shougo/neomru.vim'
on_if = 1
on_source = ['unite.vim', 'denite.nvim']
hook_source = '''
  let g:neomru#file_mru_limit = 20000
'''

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_if = 1
on_event = 'TextYankPost'
on_source = ['unite.vim', 'denite.nvim']

[[plugins]]
repo = 'Shougo/neosnippet'
depents = ['neosnippet-snippets', 'context_filetype.vim']
on_i = 1
on_ft = 'snippet'

[[plugins]]
repo = 'osyo-manga/vim-monster'
on_ft = 'ruby'

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = 'ruby'

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = 'coffeeScript'

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = 'javascript.jsx'

[[plugins]]
repo = 'mxw/vim-jsx'
on_ft = 'javascript.jsx'

[[plugins]]
repo = 'moll/vim-node'
on_ft = 'node'

[[plugins]]
repo = 'digitaltoad/vim-pug'
on_ft = ['slim', 'jade', 'pug']

[[plugins]]
repo = 'mattn/emmet-vim'
on_i = 1

[[plugins]]
repo = '5t111111/neat-json.vim'
on_ft = 'json'

[[plugins]]
repo = 'othree/html5.vim'
on_ft = 'html'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = 'css'

[[plugins]]
repo = 'cakebaker/scss-syntax.vim'
on_ft = 'scss'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'
