balias sudo "sudo "
balias v vim
balias vi vim
balias nv nvim
balias sed gsed
balias tm tmux
balias mux tmuxinator

balias g git
balias gst "git status"
balias ga "git add"

balias gb "git branch"
balias gba "git branch -a"
balias gbd "git branch -d"
balias gbl "git blame -b -w"
balias gbnm "git branch --no-merged"
balias gbr "git branch --remote"
balias gbs "git bisect"
balias gbsb "git bisect bad"
balias gbsg "git bisect good"
balias gbsr "git bisect reset"
balias gbss "git bisect start"

balias gc "git commit -v"
balias gc! "git commit -v --amend"
balias gcn! "git commit -v --no-edit --amend"
balias gca "git commit -v -a"
balias gca! "git commit -v -a --amend"
balias gcan! "git commit -v -a --no-edit --amend"
balias gcans! "git commit -v -a -s --no-edit --amend"
balias gcam "git commit -a -m"
balias gcsm "git commit -s -m"
balias gcb "git checkout -b"
balias gcf "git config --list"
balias gcl "git clone --recursive"
balias gclean "git clean -fd"
balias gcm "git checkout master"
balias gcd "git checkout develop"
balias gcmsg "git commit -m"
balias gco "git checkout"
balias gcount "git shortlog -sn"

balias gd "git diff"
balias gdca "git diff --cached"
balias gdct "git describe --tags `git rev-list --tags --max-count=1`"
balias gdt "git diff-tree --no-commit-id --name-only -r"
balias gdw "git diff --word-diff"

balias gf "git fetch"
balias gfa "git fetch --all --prune"
balias gfo "git fetch origin"

balias gl "git pull"
balias glg "git log --stat"
balias glgp "git log --stat -p"
balias glgg "git log --graph"
balias glgga "git log --graph --decorate --all"
balias glgm "git log --graph --max-count=10"
balias glo "git log --oneline --decorate"
balias glog "git log --oneline --decorate --graph"
balias gloga "git log --oneline --decorate --graph --all"

balias gm "git merge"
balias gmom "git merge origin/master"
balias gmt "git mergetool --no-prompt"
balias gmtvim "git mergetool --no-prompt --tool=vimdiff"
balias gmum "git merge upstream/master"

balias gp "git push"
balias gpd "git push --dry-run"
balias gpu "git push upstream"
balias gpv "git push -v"

balias gr "git remote"
balias gra "git remote add"
balias grb "git rebase"
balias grba "git rebase --abort"
balias grbc "git rebase --continue"
balias grbi "git rebase -i"
balias grbm "git rebase master"
balias grbs "git rebase --skip"
balias grh "git reset HEAD"
balias grhh "git reset HEAD --hard"
balias grmv "git remote rename"
balias grrm "git remote remove"
balias grset "git remote set-url"
balias gru "git reset --"
balias grup "git remote update"
balias grv "git remote -v"

balias gsb "git status -sb"
balias gsd "git svn dcommit"
balias gsi "git submodule init"
balias gsps "git show --pretty=short --show-signature"
balias gsr "git svn rebase"
balias gss "git status -s"
balias gst "git status"
balias gsta "git stash save"
balias gstaa "git stash apply"
balias gstc "git stash clear"
balias gstd "git stash drop"
balias gstl "git stash list"
balias gstp "git stash pop"
balias gsts "git stash show --text"
balias gsu "git submodule update"

balias gts "git tag -s"
balias gtv "git tag | sort -V"

balias gfx "git fixup"
balias gbra "git branch-list"

balias ls exa
balias ll "exa -GaF"
balias la "ls -la"
